language: objective-c
cache:
- bundler
- cocoapods
osx_image: xcode7.1
sudo: false
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -workspace iOSTravisSample.xcworkspace -scheme iOSTravisSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild -workspace iOSTravisSample.xcworkspace -scheme iOSTravisSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
