language: objective-c
cache: bundler
script:
- xctool -workspace iOSTravisSample.xcworkspace -scheme iOSTravisSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace iOSTravisSample.xcworkspace -scheme iOSTravisSampleTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
